### ISSUE TITLE
Compatibilidad con RAGE...

### ISSUE THREAD

**Issue by RubeGamerV** [BraveHearts/Revisiones-y-Problemas#26]
Inicio de compatibilidad con mapas de RAGE, Blitz y Ghost Squadron

**Comment by RubeGamerV** [comment]
Se necesitaran mapas de Rage para hacer pruebas. @AsdeMC y @MCChull

**Comment by AsdeMC** [comment]
los mapas los puedo conseguir yo, el problema es quitarles el mundo plano por que cuando copio un mapa viene como defecto en un mundo extrplano

**Comment by RubeGamerV** [comment]
Lo modificare yo con multiverse, creando un mundo de vacio y luego los pego
